### ISSUE TITLE
Synatax error in /UniMath/MoreFoundations/PartA.v and cannot make

### ISSUE THREAD

**Issue by Alizter** [UniMath/UniMath#978] opened 2018-05-02 11:18 UTC
I have tried to make the latest version of UniMath as of now, however I seem to get an error and I have tried updating all possible things I can think of:

```
make
! ( git diff --stat master -- UniMath/Foundations | grep . )
make -f build/CoqMakefile.make all
make[1]: Entering directory '/home/ali/UniMath'
COQC UniMath/MoreFoundations/PartA.v
File "./UniMath/MoreFoundations/PartA.v", line 43, characters 5-6:
Error:
Syntax error: [vernac:query_command] or [tactic:ltac_info] or [tactic:tactic] expected (in [vernac:tactic_command]).

build/CoqMakefile.make:644: recipe for target 'UniMath/MoreFoundations/PartA.vo' failed
make[2]: *** [UniMath/MoreFoundations/PartA.vo] Error 1
build/CoqMakefile.make:317: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ali/UniMath'
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

```

My guess is that this is coq version issue but I was under the impression that UniMath handled all those?

**Comment by benediktahrens** [comment] 2018-05-02 11:40
Travis says that the current master compiles fine:
https://travis-ci.org/UniMath/UniMath/builds/372999812
It also works on my machine.

It is hence likely that this problem is specific to your setup, and not a bug in UniMath.

I would hence kindly ask you to raise your problem on the UniMath mailing list (univalent-mathematics@googlegroups.com), so that people there can help you out. Thanks a lot in advance!

I am closing this issue.

**Closed by benediktahrens** 2018-05-02 11:40 UTC

**Comment by Alizter** [comment] 2018-05-02 14:33
I have fixed it now, I reinstalled UniMath and it is working fine. I think I messed something up when trying to update. Perhaps something could be added to the documentation to make updates easier?

Thank you anyway!

**Comment by DanGrayson** [comment] 2018-05-02 20:01
Well, what did you see in the file where the error message indicated a problem?
```
File "./UniMath/MoreFoundations/PartA.v", line 43, characters 5-6:
```
