### ISSUE TITLE
Reversible coercions

### ISSUE THREAD

**Issue by nmvdw** [UniMath/UniMath#1854] opened 2024-02-28 11:50 UTC
Due to a bug in Coq, some coercions were automatically reversible even though they should not have been according to the specification (https://github.com/UniMath/UniMath/pull/1850). For this reason, some coercions are reversible according to Coq even though that is not intended. These coercions should be made non reversible.

**Comment by nmvdw** [comment] 2024-03-21 14:00
@rmatthes This issue is solved, right?

**Comment by arnoudvanderleer** [comment] 2024-08-13 13:09
@nmvdw Is this issue solved? (Can we just check the CI warnings for this?)

**Comment by arnoudvanderleer** [comment] 2024-08-19 08:01
Ah, this is unintended behaviour, which will be fixed in coq 8.20. Then we should remove the `#[reversible=no]` annotations again, after which we can close this issue.

**Closed** 2024-09-24 19:54 UTC
