### ISSUE TITLE
Against usage of `now`.

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#609] opened 2017-02-24 14:53 UTC
Sometimes, things break at a line starting with `now`. 
That often means that one or several hypotheses, previously successfully applied by `now`, look different now. But it is not recorded which are hypotheses applied by `now`.
That makes it very difficult and annoying to debug such breakage. Please stop using that tactical.
@mortberg

**Comment by mortberg** [comment] 2017-02-24 15:01
But that's the whole point of using `now`... One wants to quickly find exactly where things break if hypotheses change. Do you have some example?

**Comment by benediktahrens** [comment] 2017-02-24 15:08
On 02/24/2017 04:02 PM, Anders Mörtberg wrote:
> But that's the whole point of using `now`... One wants to quickly
> find exactly where things break if hypotheses change. Do you have
> some example?

Absolutely: go to branch 'adjunction' and see the 'admit' that I have
temporarily put into the file CT/Adjunctions.v

**Comment by DanGrayson** [comment] 2017-02-24 15:12
This proposed prohibition of "now" seems to be a complaint that could be leveled against the use any tactic that finds a proof for us.  But the natural progression will be for us to use smarter and smarter tactics, so we don't have to find them.

**Comment by benediktahrens** [comment] 2017-02-24 15:12
On 02/24/2017 04:02 PM, Anders Mörtberg wrote:
> But that's the whole point of using `now`... One wants to quickly
> find exactly where things break if hypotheses change. Do you have
> some example?

Your remark is a bit misleading, in the following sense:
`now` does two things

1. some proof automation
2. check that the tactic finishes the subgoal

However, we are already using bullets to achieve 2., and we (I?) do not
want 1., for exactly the reason that when things break, it becomes
difficult to debug.

**Comment by mortberg** [comment] 2017-02-24 15:12
If I understand it correctly the problem would have been the same if I would have used `assumption` as well right?

**Comment by mortberg** [comment] 2017-02-24 15:13
I guess using `exact bla.` would have been perfect here?

**Comment by benediktahrens** [comment] 2017-02-24 15:14
On 02/24/2017 04:12 PM, Anders Mörtberg wrote:
> If I understand it correctly the problem would have been the same if
> I would have used `assumption` as well right?

I understand what assumption does, but I don't know what `now` does.
`assumption` did not work in the case where I got stuck.

**Comment by benediktahrens** [comment] 2017-02-24 15:15
On 02/24/2017 04:13 PM, Anders Mörtberg wrote:
> I guess using `exact bla.` would have been perfect here?

`apply` or `exact` are much more informative than `assumption` or `now`.

**Comment by vladimirias** [comment] 2017-02-24 15:16
> On Feb 24, 2017, at 10:12 AM, Daniel R. Grayson <notifications@github.com> wrote:
> 
> But the natural progression will be for us to use smarter and smarter tactics, so we don't have to find them.

Not necessarily. There are different viewpoints on this. Thierry Coquand, for example, is strongly against any automation that is not an application of a reproducible algorithm (please correct me Thierry if I misunderstood). My position is close to Thierry’s position on this question.

**Comment by vladimirias** [comment] 2017-02-24 15:17
“assumption” is a suspicious tactic. What if there are two assumptions that fit the goal and the goal is not an h-prop?

**Comment by DanGrayson** [comment] 2017-02-24 15:38
Re: "Not necessarily. There are different viewpoints on this. Thierry Coquand, for example, is strongly against any automation that is not an application of a reproducible algorithm (please correct me Thierry if I misunderstood). My position is close to Thierry’s position on this question."

That might be good advice, but if we were to follow that advice we would stop using "apply", which behaves mysteriously and changes as Coq is upgraded, and interacts badly with primitive projections.  And maybe we should.

Maybe a better word than "reproducible" would be well defined, publicly stated, and static, so that any change in behavior would be a bug.

**Comment by DanGrayson** [comment] 2017-02-24 15:40
Re: "“assumption” is a suspicious tactic. What if there are two assumptions that fit the goal and the goal is not an h-prop?"

I did an experiment:
```
Section A.
  Context (i j k l:nat).
  Definition z : nat. assumption. Defined.
  Print z.
```
The output from Print was
```
z = l
     : nat
```

So it searches the context from right to left and uses the first one it finds.  Which is all it really can do, if the context is stored as a linked list.

The documentation doesn't specify the behavior.

**Comment by benediktahrens** [comment] 2017-02-24 15:42
On 02/24/2017 04:38 PM, Daniel R. Grayson wrote:
> Re: "Not necessarily. There are different viewpoints on this. Thierry
> Coquand, for example, is strongly against any automation that is not
> an application of a reproducible algorithm (please correct me Thierry
> if I misunderstood). My position is close to Thierry’s position on
> this question."
> 
> That might be good advice, but if we were to follow that advice we
> would stop using "apply", which behaves mysteriously and changes as
> Coq is upgraded, and interacts badly with primitive projections.  And
> maybe we should.
> 
> Maybe a better word than "reproducible" would be well defined,
> publicly stated, and static, so that any change in behavior would be
> a bug.


`apply` takes an argument, and knowing that argument is very helpful to
the reader.

**Comment by mortberg** [comment] 2017-02-24 15:44
I agree with Benedikt and will stop using `now` from now on (no pun intended). It is indeed better to use `apply` or `exact`.

The definition of `now` is far too complicated (see https://coq.inria.fr/library/Coq.Init.Tactics.html). Maybe we could override it so that we have a version of `now` that tries a few simple things like `reflexivity`, `exact` and `assumption` or something like that. Maybe one could also override `assumption` so that it fails if there are more than one applicable hypothesis.

**Comment by DanGrayson** [comment] 2017-02-24 15:47
Re: "but I don't know what `now` does."

That's strange.  I failed to find "now" in the manual and in the source code.  Where does it come from?  Not from us.

**Comment by mortberg** [comment] 2017-02-24 15:49
PS: The main reason I was using `now` was that it checked that the goal was finished and not because of automation. I'm also not a fan of automation, especially relying on automation provided to us by Coq. If we write our own tactics (as I suggested above) we are in control and understand what happens, but if we use a complicated tactic for automation there is a risk that it changes and our proofs break. 

PPS: @DanGrayson click the link I posted in my message above and search for now or easy.

**Comment by DanGrayson** [comment] 2017-02-24 15:57
Oh, it's a "tactic notation", thanks for the link.

The definition is completely specified at the link, so it fulfills Thierry's criterion, unless one of the tactics it calls upon does not.  If so, which one?  If not, then if it changes, no worry, it's defined at top level so we can easily recover the old definition.

I still like using "now".  However, we may prefer to introduce our own simpler definition of it that calls upon fewer other tactics.

**Comment by vladimirias** [comment] 2017-02-24 16:20
> On Feb 24, 2017, at 10:38 AM, Daniel R. Grayson <notifications@github.com> wrote:
> 
> Maybe a better word than "reproducible" would be well defined, publicly stated, and static, so that any change in behavior would be a bug.

Yes, maybe it is a better characterization.

**Comment by mortberg** [comment] 2017-02-25 10:34
What was the conclusion of this discussion? 

I see the value in not using the `now` tactic from Coq and will try not to use it from now on. But I think it would be good to have our own and simple `now` tactic. Like I said in some message we could also redefine some of the other simple standard tactics so that they are sure to do what we expect them to. For example we could add this somewhere early on:
```
Ltac reflexivity := apply idpath.
```

**Comment by vladimirias** [comment] 2017-02-25 11:23
This one should probably go into the Preamble.v

**Comment by benediktahrens** [comment] 2017-02-25 11:58
On 02/25/2017 11:34 AM, Anders Mörtberg wrote:
> What was the conclusion of this discussion? 
> 
> I see the value in not using the `now` tactic from Coq and will try not to use it from now on. But I think it would be good to have our own and simple `now` tactic. Like I said in some message we could also redefine some of the other simple standard tactics so that they are sure to do what we expect them to. For example we could add this somewhere early on:
> ```
> Ltac reflexivity := apply idpath.
> ```

Yeah, that would save us one character each time!

**Comment by vladimirias** [comment] 2017-02-25 12:03
It might also be good (in a separate PR) to place in the preamble a list of the Agda-mode commands for the unicode notations used in the main part of the library (certainly for the ones used in Foundation) as well, maybe, with the explanation for these notations.  

Then put a reference to this to the README.

It will make it straightforward to find what a certain notation mean for someone who is unfamiliar with emacs or uses CoqIDE.

Maybe, instead of preamble it should be a separate file placed near the Preamble in the hierarchy.

**Comment by DanGrayson** [comment] 2017-02-25 13:50
Don't forget that ProofGeneral displays "reflexivity" in a beautiful red,
too, which is a great advantage.

**Comment by DanGrayson** [comment] 2017-02-25 14:11
Having our own "now" sooner rather than later is probably a good idea.  If
people agree, make an issue out of
it.  Here is a template to use to get a start:

```
Ltac unimath_easy :=
  let rec use_hyp H :=
    match type of H with
    | _ /\ _ => exact H || destruct_hyp H
    | _ => try solve [inversion H]
    end
  with do_intro := let H := fresh in intro H; use_hyp H
  with destruct_hyp H := case H; clear H; do_intro; do_intro in
  let rec use_hyps :=
    match goal with
    | H : _ /\ _ |- _  => exact H || (destruct_hyp H; use_hyps)
    | H : _ |- _ => solve [inversion H]
    | _ => idtac
    end in
  let do_atom :=
    solve [ trivial with eq_true | reflexivity | symmetry; trivial |
contradiction ] in
  let rec do_ccl :=
    try do_atom;
    repeat (do_intro; try do_atom);
    solve [ split; do_ccl ] in
  solve [ do_atom | use_hyps; do_ccl ] ||
  fail "Cannot solve this goal".

Tactic Notation "now" tactic(t) := t; unimath_easy.

Goal unit.
  now idtac.
Defined.
```

**Comment by DanGrayson** [comment] 2017-02-25 14:13
Coq has the concept of "reserving" a notation for further use.  Probably
all official unimath notations should be reserved in the Preamble (or
better, in a file required by the Preamble), too, and that would fit in
with your proposal.

**Comment by DanGrayson** [comment] 2017-02-25 23:50
Re: "Ltac reflexivity := apply idpath."

This will break proofs, because the original tactic will introduce variables until it gets to an identity type.  Let's leave it.

**Comment by mortberg** [comment] 2017-02-26 10:09
Yeah, I guess my suggestion was a little too naive. I think it's worth to think about making a set of standard UniMath tactics, but I don't really have time to do it now and it's something that needs a lot of careful consideration. We of course already have something (it's a subset of the Coq tactics with some of our own tactics (`mkpair`, `etrans`...), but it would be nice to make this explicit and clarify the semantics of the tactics (I'm imagining having a file describing which tactics are allowed, maybe redefining some Coq tactics so that they do exactly what we want.

My point about redefining reflexivity wasn't to save one character but that we are already using a standard Coq tactic that at least I don't understand exactly how it works (how does it know that it should use idpath for the UniMath equality type? does it do something more than introducing variables?). Other Coq tactics that we could consider redefining are `symmetry`, `transitivity` and maybe even `destruct` (can we define it so that it isn't using `match` but the eliminator? maybe using `induction`?). But for now let's just start by defining our own `now`? Maybe Dan could make a version of `unimath_easy` that doesn't use any forbidden tactics (removing `case` and maybe also `inversion` from the suggestion above).

**Comment by benediktahrens** [comment] 2017-02-26 11:23
On 02/26/2017 11:09 AM, Anders Mörtberg wrote:
> 
> My point about redefining reflexivity wasn't to save one character
> but that we are already using a standard Coq tactic that at least I
> don't understand exactly how it works (how does it know that it
> should use idpath for the UniMath equality type? does it do something
> more than introducing variables?). Other Coq tactics that we could
> consider redefining are `symmetry`, `transitivity` and maybe even
> `destruct` (can we define it so that it isn't using `match` but the
> eliminator? maybe using `induction`?). But for now let's just start
> by defining our own `now`? Maybe Dan could make a version of
> `unimath_easy` that doesn't use any forbidden tactics (removing
> `case` and maybe also `inversion` from the suggestion above).

What would be the purpose of the `now` tactic you are envisioning?

**Comment by mortberg** [comment] 2017-02-26 12:19
If I write `now tac` I want this to mean that `tac` finish the subgoal modulo some trivial things. So `now` should run for example reflexivity, symmetry, assumption after running `tac`. A better name might be `by`, so that when I write `by tac` it reads like "the subgoal is finished by tac`. I'm not sure if `by` will be displayed in nice red color though... 

Another nice thing with having a tactic like `unimath_easy` is that one will be able to overwrite it so that for example when one is working in a decidable theory (e.g. reasoning about rings) it can also call a decision procedure. So for example if my tactic `tac` produces a goal looking like `x + y = y + x` in a commutative ring `unimath_easy` will solve it and I can simply type `now tac` to finish off my subgoal.

It might also be a good idea to redefine `exact H` as `now apply H`.

Finally, maybe we want our unimath_easy to be closer to the ssreflect tactic `done`:
```
Ltac done :=
  trivial; hnf; intros; solve
   [ do ![solve [trivial | apply: sym_equal; trivial]
         | discriminate | contradiction | split]
   | case not_locked_false_eq_true; assumption
   | match goal with H : ¬ _ |- _ ⇒ solve [case H; trivial] end ].
```

**Comment by DanGrayson** [comment] 2017-02-26 12:23
Re: reflexivity : " I don't understand exactly how it works (how does it know that it should use idpath for the UniMath equality type?"

I checked the source code and found a comment.  Basically, after  introducing variables, it checks whether it's an inductive type with just one constructor, then tries to use that one.  So it will also work if the goal is to get an element of "unit".

**Comment by DanGrayson** [comment] 2017-02-26 12:25
Re: It might also be a good idea to redefine exact H as now apply H.

No, in my branch on the essential foundations I changed the definition of "isaset", and now I have to change 300 uses of "apply" to "exact".  The point is that sometimes "apply" will fail without adding enough blank spots.  I.e., "apply f" may fail when "apply (f _)" succeeds.

And between 8.5 and 8.6 "apply" has gotten worse.

**Comment by DanGrayson** [comment] 2017-02-26 12:31
Re: "If I write now tac I want this to mean that tac finish the subgoal modulo some trivial things. "

That's what it currently means.  Why change it?  Do you want more trivial things tried or fewer?

**Comment by mortberg** [comment] 2017-02-26 13:00
Re: It might also be a good idea to redefine exact H as now apply H.

Maybe you can redefine apply so that it looks like `use` (ie try to apply with f applied with more and more underscores)? Also the fact that apply got worse between 8.5 and 8.6 is very annoying, one would expect things to get better and not worse... Did anyone discuss this with the Coq devs?


Re:That's what it currently means. Why change it? Do you want more trivial things tried or fewer?

It's currently doing too much, for example `case` which is not allowed in UniMath. So I want it to do fewer things, also I want to code to be simple and easily understood. It should really be a simple tactic trying a few easy things, nothing fancy.

**Comment by mortberg** [comment] 2017-02-26 13:06
I made another issue about redefining `now`, see: https://github.com/UniMath/UniMath/issues/621

Maybe it's worth it to have another discussion about issues with `apply` as well. I would really like to understand what happened between 8.5 and 8.6. I don't really understand the difference between `apply`, `exact`, `refine`, `simple refine` and why we suddenly had to change a lot of code.

**Comment by DanGrayson** [comment] 2017-02-26 13:17
Re: "Maybe you can redefine apply so that it looks like use (ie try to apply with f applied with more and more underscores)? "

Something simpler works just as well: trying "exact" with more and more underscores.  So I introduced that and am calling is "use_exact".  Stay away from "apply".  It also tends to break with primitive projections on.

**Comment by DanGrayson** [comment] 2017-02-26 13:18
I think the developers don't much like "apply", because it was not designed so well, whereas "refine" is.

**Comment by DanGrayson** [comment] 2017-02-26 14:40
Here's an example the type of change I have to make everywhere in the code.  The goal is `isofhlevel 1 (identity x · f = coconeIn ccy t)`.  What used to work was `apply hsD`, where the type of hsD is `has_homsets D`.  The difference is that now the definition of "isaset" is different, but not judgmentally different.  The error message is "No applicable tactic".  If I change it to `apply (hsD _ _ _)` or to `exact (hsD _ _ _ _)` it works.

**Comment by benediktahrens** [comment] 2017-02-26 14:42
On 02/26/2017 03:40 PM, Daniel R. Grayson wrote:
> Here's an example the type of change I have to make everywhere in the
> code.  The goal is `isofhlevel 1 (identity x · f = coconeIn ccy t)`.
> What used to work was `apply hsD`, where the type of hsD is
> `has_homsets D`.  The difference is that now the definition of
> "isaset" is different, but not judgmentally different.  The error
> message is "No applicable tactic".  If I change it to `apply (hsD _ _
> _)` or to `exact (hsD _ _ _ _)` it works.
> 

I am missing some context: what change entails that you need to do those
changes?

**Comment by DanGrayson** [comment] 2017-02-26 14:44
I changed the definition of isaset to "isofhlevel 2".

**Comment by DanGrayson** [comment] 2017-02-26 16:56
Here's an example of a change I had to make due only to using 8.6 instead of 8.5:
```
@@ -532,7 +532,7 @@ Section def_opposites'.
       use unique_exists.
       + rewrite <- ZeroArrow_opp in H'. exact (CokernelOut Z CK w h H').
       + cbn. use CokernelCommutes.
-      + intros y0. apply (has_homsets_opp hs _ _ _ _).
+      + intros y0. exact (has_homsets_opp hs _ _ _ _).
       + cbn. intros y0 X. use CokernelOutsEq. rewrite CokernelCommutes. exact X.
   Qed.
 
```

**Comment by DanGrayson** [comment] 2017-02-28 01:58
this issue has been superceded by #621, closing

**Closed by DanGrayson** 2017-02-28 01:58 UTC
