### ISSUE TITLE
Moving a file

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#406] opened 2016-07-09 22:45 UTC
HLevel_n_is_of_hlevel_Sn.v should not be in category theory, it should be in Foundations.

**Comment by benediktahrens** [comment] 2016-07-11 09:17
On 07/10/2016 12:45 AM, Vladimir Voevodsky wrote:
> HLevel_n_is_of_hlevel_Sn.v should not be in category theory, it should be in Foundations. 

Absolutely. However, we should first reorganize Foundations as per issue
#350 , and then move this file to the adequate spot.

**Comment by benediktahrens** [comment] 2017-02-21 22:32
Duplicate of #523 , closing this one.

**Closed by benediktahrens** 2017-02-21 22:32 UTC
