### ISSUE TITLE
Please help debug ltac induced error

### ISSUE THREAD

**Issue by jmikedupont2** [UniMath/UniMath#1835] opened 2024-01-31 22:41 UTC
Making no changes to the source code except to insert ltact debug statements triggered this failure way down stream 
```
File "./UniMath/OrderTheory/DCPOs/Basis\
/Basis.v", line 417, characters 2-6:
Error: Illegal application:               The term "@Prelude.reverse_coercion" of type                                        "∏ T' T : Type,
  T' → Prelude.ReverseCoercionSource T → Prelude.ReverseCoercionTarget T'"
cannot be applied to the terms
 "dcpo_struct (pr1 X)" : "UU"              "dcpo" : "UU"
 "pr2 X" : "dcpo_struct (pr1 X)"
 "X" : "dcpo"                             The 1st term has type "UU" which should be a subtype of
"Type".```

**Comment by jmikedupont2** [comment] 2024-01-31 22:42
https://github.com/meta-introspector/UniMath/pull/18 here is my branch and i added the error to the line of code in debug

**Comment by jmikedupont2** [comment] 2024-01-31 23:20
I encounted this again 
```
File "./UniMath/OrderTheory/DCPOs/Basis/Basis.v", line 433, characters 2-6:
Error: Illegal application:
The term "@Prelude.reverse_coercion" of type                                        "∏ T' T : Type,                            T' → Prelude.ReverseCoercionSource T → \Prelude.ReverseCoercionTarget T'"
cannot be applied to the terms
 "dcpo_struct (pr1 X)" : "UU"
 "dcpo" : "UU"
 "pr2 X" : "dcpo_struct (pr1 X)"           "X" : "dcpo"
The 1st term has type "UU" which should be a subtype of                            "Type".
```

**Comment by arnoudvanderleer** [comment] 2024-09-21 05:10
Hi, I am very sorry about the long wait. Is this still relevant? I.e. are you still working on this or related material?

**Comment by arnoudvanderleer** [comment] 2024-10-25 14:05
Closing this as "no longer relevant"

**Comment by jmikedupont2** [comment] 2024-10-26 15:15
I am not working on this right now, but it would be nice to know how to support meta-coq like reflection in unimath? I ran into all types of issues with the venacular clashing.

**Comment by jmikedupont2** [comment] 2024-10-28 23:43
I cannot help but think there might be a built in unimath way to do term and proof reflection? do you know of any?

**Comment by arnoudvanderleer** [comment] 2024-10-29 06:51
All right, I am not very familiar with term and proof reflection. But can you elaborate a bit on what you mean by this? What was the goal that you tried to achieve?

**Comment by jmikedupont2** [comment] 2024-10-30 03:56
Have you ever used metacoq? I have achived the goal of meta-coq extraction of unimath https://github.com/meta-introspector/UniMath/tree/hack/metacoq  via a very complex merging. I am not sure exactly if it relates to this particular issue, it has been a long time, but the general goal is to be able to extract your proof into ocaml, haskell, rust etc. https://coq.inria.fr/doc/V8.11.1/refman/addendum/extraction.html
While working on this goal i encountered a bunch of errors, this I think was one of the.

**Comment by jmikedupont2** [comment] 2024-10-30 03:59
Have you ever used metacoq? I have achived the goal of meta-coq extraction of unimath https://github.com/meta-introspector/UniMath/tree/hack/metacoq  via a very complex merging. I am not sure exactly if it relates to this particular issue, it has been a long time, but the general goal is to be able to extract your proof into ocaml, haskell, rust etc. https://coq.inria.fr/doc/V8.11.1/refman/addendum/extraction.html
While working on this goal i encountered a bunch of errors, this I think was one of the.

**Comment by jmikedupont2** [comment] 2024-10-30 04:00
Looking at this error, I remember it was another approach to use ltac debug statements to get traces of the code, doing so changed the behaviour in a strange way. this attempt was to extract traces of the proof in debug mode without meta-coq.

**Comment by arnoudvanderleer** [comment] 2024-10-30 05:32
Hm, right. I have never used metacoq, but at least I now know what you are talking about. As far as I know, there is no standard UniMath way to do this.

Out of curiosity: what kind of things would you want to prove / study with metacoq / these traces?

**Comment by arnoudvanderleer** [comment] 2024-10-30 05:38
Ah, I've taken another glance at your errors. I now realize that this is a problem that many tools run into: type-in-type.
For some reason (which I am not entirely sure about), UniMath has been built on the assumption that `UU` has type `UU`. This is, of course, unsound, but if you are careful, the mathematics you write will still be valid. Therefore, UniMath can only be compiled with the flag `-type-in-type` enabled, and any tool that operates on UniMath must be compatible with this.

What happens if you do what you did, but also add an export of `Unset universe checking` to `Init` (see [#1697](https://github.com/UniMath/UniMath/pull/1697/files#diff-bac161a271f814352da82851bc4e77952e20acbfad62b073751442ce5a40e9d4))?

**Comment by arnoudvanderleer** [comment] 2024-10-30 10:05
Anyhoo. I believe the problem is due to type-in-type. I am not sure whether the tools you are using are compatible with it in some way or not (as I said, you could try to set `export universe checking` in `Init`).
Either way, it is out of our hands, so I will close this thread.
Still, I would be interested in an update about whether you get it to work.

**Closed by arnoudvanderleer** 2024-10-30 10:05 UTC

**Comment by jmikedupont2** [comment] 2024-10-30 14:58
https://github.com/meta-introspector/unimath-comic/issues/1 here is what i was working on with the ltac traces, feeding them in chunks to llms to produce descriptions, it was quite interesting, there is a data set on hugging face with traces of unimath proofs
