### ISSUE TITLE
Travis frequently returns false positives due to difficulties installing opam

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#858] opened 2017-12-24 16:23 UTC
This error frequently occurs:
```
$ bash -c 'echo $BASH_VERSION'
4.3.11(1)-release
29.66s$ opam init --yes --no-setup
default    Downloading https://opam.ocaml.org/urls.txt
default    Downloading https://opam.ocaml.org/index.tar.gz
[ERROR] No OCaml compiler found in path. You should use:
    opam init --comp=VERSION
'opam init --yes --no-setup' failed.
The command "opam init --yes --no-setup" failed and exited with 66 during .
```
This is annoying since consequently Travis signals a build failure, requiring manual restart of the build.
Is there a way to make the Travis build more resistant to this, e.g., by having it attempt to install opam more than once?

**Comment by benediktahrens** [comment] 2017-12-24 16:25
As an example, see https://travis-ci.org/UniMath/UniMath/jobs/321055588 - I am purposefully not restarting the build.

**Comment by DanGrayson** [comment] 2017-12-24 17:08
I'll try to figure this out.

**Comment by DanGrayson** [comment] 2017-12-24 17:20
It's possible that the old opam 1.1.1 that is available on Travis' old ubuntu 14.04 is too old, and the way around this is to use opam 1.2.2, which is easy to download and install from the web.  I'll submit a pull request to test the theory.

**Comment by palmskog** [comment] 2017-12-28 17:43
The problem seems to be that Travis sometimes cannot properly access the Ubuntu PPA repositories:
```
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
...
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
For example, see [this build](https://travis-ci.org/UniMath/UniMath/jobs/320394439).

Since OPAM version 1.2.2 is in one of these PPA repositories, it doesn't get properly installed. And when it doesn't get properly installed, the built-in, the obsolete OPAM version 1.1 gets used. The OPAM package repository for this OPAM stopped being maintained years ago.

I don't think this problem can be helped by switching compilers in OPAM, since I don't believe recent compilers are available in OPAM 1.1. And if OPAM 1.2.2 gets properly installed, everything works out anyway.

**Comment by palmskog** [comment] 2017-12-28 17:46
I believe this is a Travis-related issue, see for example some recent [error descriptions](https://github.com/travis-ci/travis-ci/issues/8507) of this kind in the Travis issue tracker.

**Comment by DanGrayson** [comment] 2017-12-28 18:05
I can't tell what command produced those warning messages by looking at the log of the build.  It would be nice if there were a way to convert the warning message to an error so the build would stop at that point.  What makes you think that opam 1.1 gets installed when ppa.launchpad.net is not available?

Or maybe we should have a command that examines the version number of opam and produces an error if it's not at least 1.2.2.

Specifying compiler version 4.06.0, as in #860, would be good way to cause the job to terminate early if an old opam gets installed.

**Comment by palmskog** [comment] 2017-12-28 18:15
As far as I can tell from looking at Travis builds in the Trusty environment, OPAM version 1.1 is installed by default - OPAM 1.1 is in fact the version shipped with Ubuntu Trusty. 

The OPAM 1.2.2 package from the [PPA](https://launchpad.net/~avsm) depends explicitly on OCaml 4.02.3 (a minimum requirement for OPAM 1.2.2, I believe), so if there is no OCaml compiler, the packages from the PPA were not installed properly. This is indicated by the error message `[ERROR] No OCaml compiler found in path.`

**Comment by DanGrayson** [comment] 2017-12-28 18:21
Can't we avoid ppa entirely somehow?  After all, if the network connection to it is bad, we'll always have problems.

If the opam 1.2.2 package depends on the ocaml 4.02.3 package, then the package manager should install it, but the error message seems to be from opam, not from a package manager.  Moreover, doesn't opam install its own ocaml compiler as part of its normal mode of operation?

**Comment by palmskog** [comment] 2017-12-28 18:49
A PPA is the only reasonable way to allow installing pre-built packages into "old" versions of Ubuntu, like the Trusty version Travis is using. The only reasonable alternative in my mind is to use pre-built containers with the operating system and all libraries required, e.g., Docker images. As I've said before, I think this is the correct long-term choice.

The OPAM error messages are (indirectly) caused by the apt repository `Failed to fetch` messages. Since `apt` doesn't register the newer alternative version of OCaml and OPAM, the old OPAM gets installed, and the old OPAM doesn't even have the `--compiler` option.

For as long as I've used it, Travis has never failed to download actual `.deb` packages. Therefore, I suspect (and hope) that these `Failed to fetch` errors are due to particulars in how they implement their `apt` add-on, and not due to fundamental network connectivity issues. If my theory holds, #863 should fix the problem.

**Comment by palmskog** [comment] 2017-12-28 19:53
One more corroboration of my theory: the Trusty apt [package](https://packages.ubuntu.com/trusty/ocaml/opam) for OPAM (version 1.1) doesn't require an OCaml compiler - it's only listed as "recommended". Therefore, when the PPA apt package for OPAM fails to register, only OPAM 1.1 without any OCaml compiler is installed, triggering the `[ERROR] No OCaml compiler found in path." error message.

**Comment by DanGrayson** [comment] 2017-12-28 19:57
Isn't it strange, given that opam 1.1 gives an error message when it finds no ocaml compiler, that the opam package does not list ocaml as a prerequisite?

Isn't it also strange that when the PPA apt package for OPAM fails to register, an error is not raised?

**Comment by palmskog** [comment] 2017-12-28 20:17
I'm speculating here, but I believe the requirement on having OCaml (>= 4.02.3) installed all the time was added between OPAM version 1.1 and version 1.2.2. (The OPAM Github [repo](https://github.com/ocaml/opam/) currently lists OCaml as both a compilation and runtime dependency.)

I guess the Debian/Ubuntu developers considered the situation when `apt` repositories are unreachable to not be worthy of an error code (hence, only warnings are displayed in the output). Our particular problem is that packages that already exist in obsolete versions in Trusty get replaced by identically named packages. We would have to add a manual check in the Travis script to verify that they are the proper versions to be really sure.

**Comment by benediktahrens** [comment] 2018-01-02 00:10
Something I have not seen yet:
```
[31m[ERROR][m Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/repo/default/packages/typehashlib/typehashlib.109.15.00/opam. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly.
[33m[WARNING][m Errors while parsing typehashlib.109.15.00 OPAM file, skipping.
[31m[ERROR][m Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/repo/default/packages/typehashlib/typehashlib.109.15.01/opam. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly.
[33m[WARNING][m Errors while parsing typehashlib.109.15.01 OPAM file, skipping.
[31m[ERROR][m Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/repo/default/packages/typehashlib/typehashlib.109.15.02/opam. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly.
[33m[WARNING][m Errors while parsing typehashlib.109.15.02 OPAM file, skipping.
[31m[ERROR][m File "/home/travis/.opam/repo/default/packages/typehashlib/typehashlib.109.15.04/opam", line 11, character 25-27: parse error.
[33m[WARNING][m Errors while parsing typehashlib.109.15.04 OPAM file, skipping.
[31m[ERROR][m File "/home/travis/.opam/repo/default/packages/typerep/typerep.109.55.00/opam", line 23, character 25-27: parse error.
[33m[WARNING][m Errors while parsing typerep.109.55.00 OPAM file, skipping.
[31m[ERROR][m File "/home/travis/.opam/repo/default/packages/typerep/typerep.109.55.02/opam", line 23, character 25-27: parse error.
[33m[WARNING][m Errors while parsing typerep.109.55.02 OPAM file, skipping.
[31m[ERROR][m File "/home/travis/.opam/repo/default/packages/typerep/typerep.111.06.00/opam", line 22, character 25-27: parse error.
[33m[WARNING][m Errors while parsing typerep.111.06.00 OPAM file, skipping.
[31m[ERROR][m File "/home/travis/.opam/repo/default/packages/typerep/typerep.111.17.00/opam", line 22, character 25-27: parse error.
[33m[WARNING][m Errors while parsing typerep.111.17.00 OPAM file, skipping.
[31m[ERROR][m File "/home/travis/.opam/repo/default/packages/typerep/typerep.112.06.00/opam", line 22, character 25-27: parse error.
[33m[WARNING][m Errors while parsing typerep.112.06.00 OPAM file, skipping.
[31m[ERROR][m File "/home/travis/.opam/repo/default/packages/typerep/typerep.112.17.00/opam", line 18, character 25-27: parse error.
[33m[WARNING][m Errors while parsing typerep.112.17.00 OPAM file, skipping.


The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```
while building current master, see, e.g.,
https://travis-ci.org/UniMath/UniMath/jobs/323968285

**Comment by DanGrayson** [comment] 2018-01-02 00:59
Again the avsm PPA couldn't be connected to.  Maybe the first thing we should do with opam is to check the version number, and if it's not at least 1.2, bomb out.  That would at least reduce the variety of error messages we see.

**Comment by palmskog** [comment] 2018-01-09 09:05
@DanGrayson @benediktahrens for the last few days, we've successfully been using custom Docker images in the various [Verdi](https://github.com/uwplse/verdi) projects to get rid of these Travis connection errors. I adapted this approach to make a custom Docker image for UniMath, see #866. If the Travis build logs look good to you, this could be a permanent solution.

**Comment by DanGrayson** [comment] 2018-12-21 02:10
I guess not, closing.

**Closed by DanGrayson** 2018-12-21 02:10 UTC
