### ISSUE TITLE
Who are contributors anonymous-1234567 and anonymous-13243557?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1821] opened 2024-01-04 17:01 UTC
We have contributions by anonymous-1234567 and anonymous-13243557, see https://github.com/UniMath/UniMath/graphs/contributors. Who are these contributors, and how can we ensure they are credited correctly?

**Comment by nmvdw** [comment] 2024-01-04 17:16
For a while, I committed with alternative e-mail addresses, namely my uni work addresses, and Github connected commits to those e-mail addresses. At some point, I created an anonymous github account to upload the documentation of a paper (https://github.com/anonymous-13243557/EnrichedCats) using `nweide@cs.ru.nl`, and then a part of my commits were connected to that account. As a test, I also made an account using `n.vanderweide@science.ru.nl`, which is 'anonymous-1234567 '. 

I did change the mailmap in git to connect those commits to me, but for some reason, the contributors graph didn't get affected by it.

**Comment by nmvdw** [comment] 2024-01-04 17:21
It seems like the mailmap is not considered by the contribution graph: https://stackoverflow.com/questions/53629125/does-github-consider-mailmap-for-contribution-graph

I will try to add the e-mail addresses to my current account.

**Comment by nmvdw** [comment] 2024-01-05 09:04
The issue is solved now, and the anonymous accounts do not appear anymore in the contribution graph.

**Closed by nmvdw** 2024-01-05 09:04 UTC
