### ISSUE TITLE
The "End of the file" lines

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#394] opened 2016-07-01 00:22 UTC
The lines (\* End of the file … _) are out of sync with the actual file names. I suggest that we replace these lines with (_ End of the file *) without the filename.

**Comment by DanGrayson** [comment] 2016-07-01 14:31
I suggest we remove those comments.  They don't add any value, at least for me.

**Comment by vladimirias** [comment] 2016-07-01 16:52
The issue was that Coq, when it reached the end of the file in emacs discharged some information, e.g. information about universes.

These lines were there so that it is easy to get to the end of the code without getting to the end of the file.

**Comment by DanGrayson** [comment] 2016-07-01 17:07
Have you seen that behavior lately?  Teach me how to reproduce it, and I'll fix it instead.  (I suppose you're referring to ProofGeneral behavior.)

**Comment by rmatthes** [comment] 2016-07-07 10:04
I often put administrative last lines into my Coq vernacular files to ensure the files end with a newline. Older diff tools would otherwise run into problems.

**Comment by DanGrayson** [comment] 2016-07-07 11:43
To have emacs require a trailing newline for you put

(setq require-final-newline t)

in your .emacs file.

I actually like having a temporary empty comment at the end of the file while I'm working on adding proofs to the file, because when I enable proof-electric-terminator-enable, so that each "." automatically executes the step just typed, and when I'm at the very end of the file,  I get an error message from ProofGeneral on the mode line that says "Error running timer `show-paren-function': (wrong-type-argument characterp nil)", and it moves the cursor back to the left of the ".".

Maybe I should debug that!

**Comment by benediktahrens** [comment] 2016-07-07 12:20
On 07/07/2016 01:43 PM, Daniel R. Grayson wrote:
> To have emacs require a trailing newline for you put
> 
> (setq require-final-newline t)
> 
> in your .emacs file.
> 
> I actually like having a temporary empty comment at the end of the
> file while I'm working on adding proofs to the file, because when I
> enable proof-electric-terminator-enable, so that each "."
> automatically executes the step just typed, and when I'm at the very
> end of the file,  I get an error message from ProofGeneral on the
> mode line that says "Error running timer `show-paren-function':
> (wrong-type-argument characterp nil)", and it moves the cursor back
> to the left of the ".".
> 
> Maybe I should debug that!

Indeed, this error message - and, more importantly, the cursor jumping -
is awful. If you know a way around that, I'd be happy to know.

**Comment by benediktahrens** [comment] 2016-07-07 12:21
On 07/07/2016 02:20 PM, Benedikt Ahrens wrote:
> On 07/07/2016 01:43 PM, Daniel R. Grayson wrote:
>>
>> I actually like having a temporary empty comment at the end of the
>> file while I'm working on adding proofs to the file, because when I
>> enable proof-electric-terminator-enable, so that each "."
>> automatically executes the step just typed, and when I'm at the very
>> end of the file,  I get an error message from ProofGeneral on the
>> mode line that says "Error running timer `show-paren-function':
>> (wrong-type-argument characterp nil)", and it moves the cursor back
>> to the left of the ".".
>>
>> Maybe I should debug that!
> 
> Indeed, this error message - and, more importantly, the cursor jumping -
> is awful. If you know a way around that, I'd be happy to know.

Oh, sorry, you give the workaround in your message, if I understand
correctly: putting an empty comment at the end of the file.

**Comment by rmatthes** [comment] 2016-07-07 12:25
Hi Dan, thanks for the good emacs hint. I added it to my .emacs file, but will still also use CoqIDE to edit vernacular files.

**Comment by DanGrayson** [comment] 2016-07-07 12:25
"Oh, sorry, you give the workaround in your message, if I understand
correctly: putting an empty comment at the end of the file."

I'll try to debug it, anyway.

**Comment by DanGrayson** [comment] 2016-07-07 12:51
@benediktahrens , the fix is to upgrade emacs!  The latest pretest version at https://emacsformacosx.com/builds works fine.  It's emacs 25.

**Comment by benediktahrens** [comment] 2017-12-07 15:52
Resolved, closing.

**Closed by benediktahrens** 2017-12-07 15:52 UTC
